name: 'Ingot Package Artifact'
description: 'Upload/Download Ingot package artifact'
author: 'Ingot'
inputs:
  type:
    description: 'The type of artifact action, either upload or download'
    required: true
runs:
  using: 'composite'
  steps:

    # We pass through one action to download/upload
    # since using inputs/outputs alters the way the
    # artifacts are downloaded and results in the
    # wrong path on artifact restore

    # -----------------------------------
    # Upload
    # -----------------------------------

    # Lists the files that will be uploaded
    # for debugging mostly
    - if: ${{ inputs.type == 'upload' }}
      name: "List Files To Upload"
      shell: sh
      # path to list should match artifact path
      run: find . -wholename ./dist/nuget/*.nupkg

    # Upload the artifact
    - if: ${{ inputs.type == 'upload' }}
      name: "Artifact Upload"
      uses: actions/upload-artifact@v4
      with:
        # Name needs to match in the download section
        name: nupkg
        if-no-files-found: error
        retention-days: 1
        path: ./dist/nuget/*.nupkg

    # -----------------------------------
    # Download
    # -----------------------------------

    # Download the artifact
    - if: ${{ inputs.type == 'download' }}
      name: "Artifact Download"
      uses: actions/download-artifact@v4
      with:
        # Name needs to match in the upload section
        # Do not specify a path to ensure the restore
        # puts the files in their original location
        name: nupkg

    # Lists the downloaded files for
    # debugging mostly
    - if: ${{ inputs.type == 'download' }}
      name: "List files Downloaded"
      shell: sh
      # path to list should match artifact path
      run: find . -wholename ./dist/nuget/*.nupkg