name: 'Ingot Setup'
description: 'Sets up the environment for the Ingot project'
author: 'Ingot'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: ./global.json
    - shell: pwsh
      name: Environment Setup
      run: |
        dotnet tool restore
        dotnet ib ci-env-setup