name: 'Ingot Setup'
description: 'Sets up the environment for the Ingot project'
author: 'Ingot'
runs:
  using: 'composite'
  steps:
    - shell: pwsh
      name: Environment Setup
      run: |
        dotnet tool restore
        dotnet ib ci-env-setup