name: 'Ingot Build Artifact Upload'
description: 'Sets up the environment for the Ingot project'
author: 'Ingot'
inputs:
  type:
    description: 'The type of artifact action, either upload or download'
    required: true
runs:
  using: 'composite'
  steps:

    # Upload section
    - name: "List Files To Upload"
      if: ${{ inputs.type == "upload" }}
      shell: sh
      run: find . -wholename ./**/bin/*
    - name: "Artifact Upload: bin"
      if: ${{ inputs.type == "upload" }}
      uses: actions/upload-artifact@v4
      with:
        name: build
        if-no-files-found: error
        retention-days: 1
        path: ./**/bin/*
    
    # Download section
    - name: "Artifact Download: bin"
      if: ${{ inputs.type == "download" }}
      uses: actions/download-artifact@v4
      with:
        name: build
    - name: "List files Downloaded"
      if: ${{ inputs.type == "download" }}
      shell: sh
      run: find . -wholename ./**/bin/*