name: 'Ingot Build Artifact Upload'
description: 'Sets up the environment for the Ingot project'
author: 'Ingot'
inputs:
  nuget-source:
    description: 'Nuget feed source'
    required: true
  nuget-api-key:
    description: 'Nuget API key'
    required: true
runs:
  using: 'composite'
  steps:

    # Downloads the package artifact
    - name: Download Package Artifacts
      uses: ./.github/actions/ingot-src/package-artifacts
      with:
        type: download
    
    # Pushes the nuget package to the defined
    # source using the specified API key
    - name: Push
      shell: sh
      run: |
        dotnet ib publish \
          -NupkgPushSource "${{ inputs.nuget-source }}" \
          -NupkgPushApiKey "${{ inputs.nuget-api-key }}"
  