name: Ingot Full

on: workflow_dispatch

jobs:

    # Builds the source code
    src-build:
        name: Build
        runs-on: windows-2022
        timeout-minutes: 5
        env:
          pwsh: pwsh
        steps:
        - name: Git Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: '0'
            filter: 'tree:0'
        - run: dotnet tool restore
        - run: dotnet ib setup
        - run: dotnet ib full
        - uses: actions/upload-artifact@v4
          with:
            name: full
            if-no-files-found: error
            retention-days: 1
            path: '**/*'
