name: Ingot Source

on:
  push:
    paths:
      - 'src/**'
      - '.github/**'
      - '.build.ps1'
    branches:
      - main
  pull_request:
    paths:
      - 'src/**'
      - '.github/**'
      - '.build.ps1'
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-test-validate:
    name: Build/Test/Validate
    uses: stfbln/ingot/.github/workflows/ingot-src-build-test-validate.yml@main

  src-publish-feedz:
    needs:
      - build-test-validate
    name: Publish (feedz.io)
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    cancel-timeout-minutes: 5
    timeout-minutes: 5
    env:
      NUPKG_DiRECTORY_OUTPUT: "./dist/nuget"
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/ingot-setup
      - name: Push
        uses: ./.github/actions/ingot-src/publish-package
        with:
          nuget-source: "https://f.feedz.io/stfbln/ingot/nuget/index.json"
          nuget-api-key: "${{ secrets.FEEDZ_API_KEY }}"
