name: Ingot Source Build/Test/Validate

on:
  workflow_call: {}

jobs:

  src-build:
    name: Build
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    timeout-minutes: 5
    steps:
      - uses: stfbln/ingot/.github/actions/ingot-setup@main
        name: Setup
      - name: Build
        run: dotnet ib build
      - name: Upload Build Artifacts
        uses: ./.github/actions/ingot-src/build-artifacts
        with:
          type: upload

  src-linter:
    needs: src-build
    name: Linter
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    timeout-minutes: 3
    steps:
      - uses: stfbln/ingot/.github/actions/ingot-setup@main
        name: Setup
      - name: Linter
        run: dotnet ib linter

  src-test:
    needs: src-build
    name: Test
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    timeout-minutes: 5
    steps:
      - uses: stfbln/ingot/.github/actions/ingot-setup@main
        name: Setup
      - name: Download Build Artifacts
        uses: ./.github/actions/ingot-src/build-artifacts
        with:
          type: download
      - name: Test
        run: dotnet ib test
      - if: '!cancelled()'
        name: Upload Test Result Artifacts
        uses: ./.github/actions/ingot-src/test-artifacts
        with:
          type: upload

  src-coverage:
    needs: src-test
    if: ${{ !cancelled() && (needs.src-test.result == 'success' || needs.src-test.result == 'failure') }}
    name: Coverage Report
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    timeout-minutes: 3
    steps:
      - uses: stfbln/ingot/.github/actions/ingot-setup@main
        name: Setup
      - name: Download Test Result Artifacts
        uses: ./.github/actions/ingot-src/test-artifacts
        with:
          type: download
      - name: Test Coverage
        run: dotnet ib coverage
      - name: Upload Coverage Artifacts
        uses: ./.github/actions/ingot-src/coverage-artifacts
        with:
          type: upload

  src-pack:
    needs: src-build
    name: Pack
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    timeout-minutes: 3
    steps:
      - uses: stfbln/ingot/.github/actions/ingot-setup@main
        name: Setup
      - name: Download Build Artifacts
        uses: ./.github/actions/ingot-src/build-artifacts
        with:
          type: download
      - name: Pack
        run: dotnet ib pack
      - name: Upload Package Artifacts
        uses: ./.github/actions/ingot-src/package-artifacts
        with:
          type: upload
