name: Ingot
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NUPKG_DiRECTORY: "./dist"

jobs:
  libs-linter:
    name: Libraries Linter
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - uses: ./.github/actions/ingot-setup
        name: Setup
      - name: Linter
        run: dotnet ib Linter

  libs-build:
    needs: libs-linter
    name: Libraries Build
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - uses: ./.github/actions/ingot-setup
        name: Setup
      - name: Build
        run: dotnet ib Build
      - uses: actions/upload-artifact@v4
        name: "Artifact: bin/Release"
        with:
          name: build
          if-no-files-found: error
          retention-days: 1
          path: ./**/bin/*
      - name: Package
        run: |
          dotnet ib Package \
            -NupkgDirectory ${{ env.NUPKG_DiRECTORY }}
      - uses: actions/upload-artifact@v4
        name: "Artifact: nupkg"
        with:
          name: nupkg
          if-no-files-found: error
          retention-days: 3
          path: ${{ env.NUPKG_DiRECTORY }}/*.nupkg

  libs-test:
    needs: libs-build
    name: Libraries Test
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - uses: ./.github/actions/ingot-setup
        name: Setup
      - uses: actions/download-artifact@v4
        with:
          name: build
      - name: Test
        run: dotnet ib Test

  libs-release:
    needs: 
      - libs-build
      - libs-test
    name: Libraries Release
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - uses: ./.github/actions/ingot-setup
        name: Setup
      - uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: ${{ env.NUPKG_DiRECTORY }}
      - name: Release (feedz.io)
        run: |
          dotnet ib Release \
            -NupkgDirectory "${{ env.NUPKG_DiRECTORY }}" \
            -NupkgPushSource "https://f.feedz.io/stfbln/ingot/nuget/index.json" \
            -NupkgPushApiKey "${{ secrets.FEEDZ_API_KEY }}"
      - name: Release (nuget.org)
        if: ${{ startsWith(github.event.ref, 'refs/tags') }}
        run: |
          dotnet ib Release \
            -NupkgDirectory "${{ env.NUPKG_DiRECTORY }}" \
            -NupkgPushSource "https://api.nuget.org/v3/index.json" \
            -NupkgPushApiKey "${{ secrets.NUGET_ORG_API_KEY }}"
