name: Ingot Source Build/Test/Validate

on:
  workflow_call: {}

env:
  MinVerDefaultPreReleaseIdentifiers: alpha.0.${{ github.run_id }}.${{ github.run_attempt}}

jobs:
  src-linter:
    name: Linter
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    timeout-minutes: 3
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/ingot-setup
        name: Setup
      - name: Linter
        run: dotnet ib ci-src-linter

  src-build:
    needs: src-linter
    name: Build
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    timeout-minutes: 5
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          # Ensures MinVer finds what it needs
          fetch-depth: 0
          filter: tree:0
      - name: Setup
        uses: ./.github/actions/ingot-setup
      - name: Build
        run: dotnet ib ci-src-build
      - name: Upload Build Artifacts
        uses: ./.github/actions/ingot-src/build-artifacts
        with:
          type: upload

  src-test:
    needs: src-build
    name: Test
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    timeout-minutes: 5
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/ingot-setup
        name: Setup
      - name: Download Build Artifacts
        uses: ./.github/actions/ingot-src/build-artifacts
        with:
          type: download
      - name: Test
        run: dotnet ib ci-src-test

  src-pack:
    needs: src-build
    name: Pack
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    timeout-minutes: 3
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          # Ensures MinVer finds what it needs
          fetch-depth: 0
          filter: tree:0
      - uses: ./.github/actions/ingot-setup
        name: Setup
      - name: Download Build Artifacts
        uses: ./.github/actions/ingot-src/build-artifacts
        with:
          type: download
      - name: Pack
        run: dotnet ib ci-src-pack
      - name: Upload Package Artifacts
        uses: ./.github/actions/ingot-src/package-artifacts
        with:
          type: upload
