name: Ingot
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  libs:
    name: Libraries
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          dotnet tool restore
          dotnet ib Setup
      - name: Build
        run: dotnet ib Build
      - name: Test
        run: dotnet ib Test
      - name: Validate
        run: dotnet ib Validate
      - name: Package
        run: dotnet ib Package
      - uses: actions/upload-artifact@v4
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 3
          path: ./dist/nuget/*.nupkg
      - name: Release
        run: dotnet ib Release
