name: Ingot Source (Release)

on:
  push:
    tags:
      - '*'

jobs:
  build-test-validate:
    name: Source
    uses: stfbln/ingot/.github/workflows/ingot-src-build-test-validate.yml@main

  src-publish-nuget-org:
    if: ${{ startsWith(github.event.ref, 'refs/tags') }}
    needs:
      - build-test-validate
    name: Source / Publish (nuget.org)
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    cancel-timeout-minutes: 5
    timeout-minutes: 5
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/ingot-setup
      - name: Push
        uses: ./.github/actions/ingot-src/publish-package
        with:
          nuget-artifact-name: ${{ needs.build-test-validate.outputs.nuget-artifact-name }}
          nuget-source: "https://api.nuget.org/v3/index.json"
          nuget-api-key: "${{ secrets.NUGET_ORG_API_KEY }}"
