name: Ingot
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NUPKG_DiRECTORY: "./dist"
  NUPKG_PUSH_SOURCE: "https://api.nuget.org/v3/index.json"
  NUPKG_PUSH_API_KEY: "${{ secrets.NUGET_ORG_API_KEY }}"
  MinVerVerbosity: "trace"

jobs:
  libs:
    name: Libraries
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    steps:
      - uses: actions/checkout@v4
        name: Git Checkout
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Environment Setup
        run: |
          dotnet tool restore
          dotnet ib Setup
      - name: Linter
        run: dotnet ib Linter
      - name: Build
        run: dotnet ib Build
      - name: Test
        run: dotnet ib Test
      - name: Package
        run: |
          dotnet ib Package \
            -NupkgDirectory ${{ env.NUPKG_DiRECTORY }}
      - uses: actions/upload-artifact@v4
        name: "Artifact: nuget (${{ env.NUPKG_DiRECTORY }}/*.nupkg)"
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 3
          path: ${{ env.NUPKG_DiRECTORY }}/*.nupkg
      - name: Release
        run: |
          dotnet ib Release \
            -NupkgDirectory ${{ env.NUPKG_DiRECTORY }} \
            -NupkgPushSource ${{ env.NUPKG_PUSH_SOURCE }} \
            -NupkgPushApiKey ${{ env.NUPKG_PUSH_API_KEY }}
