name: Ingot Source

on:
  push:
    paths:
      - 'src/**'
      - '.github/**'
      - '.build.ps1'
    branches:
      - main
  pull_request:
    paths:
      - 'src/**'
      - '.github/**'
      - '.build.ps1'
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  src-linter:
    name: Linter
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    timeout-minutes: 3
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/ingot-setup
        name: Setup
      - name: Linter
        run: dotnet ib ci-src-linter

  src-build:
    needs: src-linter
    name: Build
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    timeout-minutes: 5
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          # Ensures MinVer finds what it needs
          fetch-depth: 0
          filter: tree:0
      - name: Setup
        uses: ./.github/actions/ingot-setup
      - name: Build
        run: dotnet ib ci-src-build
      - name: Upload Build Artifacts
        uses: ./.github/actions/ingot-src/build-artifact-upload
      - name: Restore NuGet Save
        uses: actions/cache/save@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/Directory.Packages.props') }}

  src-test:
    needs: src-build
    name: Test
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    timeout-minutes: 5
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/ingot-setup
        name: Setup
      - name: Download Build Artifacts
        uses: ./.github/actions/ingot-src/build-artifact-download
      - name: Test
        run: dotnet ib ci-src-test

  src-pack:
    needs: src-build
    name: Pack
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    timeout-minutes: 3
    env:
      NUPKG_DiRECTORY_OUTPUT: "./dist/nuget"
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/ingot-setup
        name: Setup
      - name: Download Build Artifacts
        uses: ./.github/actions/ingot-src/build-artifact-download
      - name: Pack
        run: |
          dotnet ib ci-src-pack \
            -NupkgDirectory ${{ env.NUPKG_DiRECTORY_OUTPUT }}
      - uses: actions/upload-artifact@v4
        name: "Artifact: nupkg"
        with:
          name: nupkg
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.NUPKG_DiRECTORY_OUTPUT }}/*.nupkg

  src-publish-feedz:
    if: ${{ !startsWith(github.event.ref, 'refs/tags') }}
    needs:
      - src-pack
      - src-test
    name: Publish (feedz.io)
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    cancel-timeout-minutes: 5
    timeout-minutes: 5
    env:
      NUPKG_DiRECTORY_OUTPUT: "./dist/nuget"
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/ingot-setup
      - name: Push
        uses: ./.github/actions/ingot-src/publish-package
        with:
          nuget-source: "https://f.feedz.io/stfbln/ingot/nuget/index.json"
          nuget-api-key: "${{ secrets.FEEDZ_API_KEY }}"

  src-publish-nuget-org:
    if: ${{ startsWith(github.event.ref, 'refs/tags') }}
    needs:
      - src-pack
      - src-test
    name: Publish (nuget.org)
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    cancel-timeout-minutes: 5
    timeout-minutes: 5
    env:
      NUPKG_DiRECTORY_OUTPUT: "./dist/nuget"
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/ingot-setup
      - name: Push
        uses: ./.github/actions/ingot-src/publish-package
        with:
          nuget-source: "https://api.nuget.org/v3/index.json"
          nuget-api-key: "${{ secrets.NUGET_ORG_API_KEY }}"
