name: Ingot Source
on:
  push:
    paths:
      - 'src/**'
      - '.github/**'
      - '.build.ps1'
    branches:
      - main
  pull_request:
    paths:
      - 'src/**'
      - '.github/**'
      - '.build.ps1'
    branches:
      - '*'

env:
  NUPKG_DiRECTORY: "./dist"

jobs:
  src-linter:
    name: Linter
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/ingot-setup
        name: Setup
      - name: Linter
        run: dotnet ib ci-src-linter

  src-build:
    needs: src-linter
    name: Build
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          # Ensures MinVer finds what it needs
          fetch-depth: 0
          filter: tree:0
      - name: Setup
        uses: ./.github/actions/ingot-setup
      - name: Build
        run: dotnet ib ci-src-build
      - name: Upload Build Artifacts
        uses: ./.github/actions/ingot-src/build-artifact-upload

  src-test:
    needs: src-build
    name: Test
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/ingot-setup
        name: Setup
      - name: Download Build Artifacts
        uses: ./.github/actions/ingot-src/build-artifact-download
      - name: Test
        run: dotnet ib ci-src-test

  src-pack:
    needs: src-build
    name: Pack
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/ingot-setup
        name: Setup
      - name: Download Build Artifacts
        uses: ./.github/actions/ingot-src/build-artifact-download
      - name: Pack
        run: |
          dotnet ib ci-src-pack \
            -NupkgDirectory ${{ env.NUPKG_DiRECTORY }}
      - uses: actions/upload-artifact@v4
        name: "Artifact: nupkg"
        with:
          name: nupkg
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.NUPKG_DiRECTORY }}/*.nupkg

  src-publish:
    needs:
      - src-pack
      - src-test
    name: Publish
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/ingot-setup
        name: Setup
      - uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: ${{ env.NUPKG_DiRECTORY }}
      - name: Push (feedz.io)
        run: |
          dotnet ib ci-src-publish \
            -NupkgDirectory "${{ env.NUPKG_DiRECTORY }}" \
            -NupkgPushSource "https://f.feedz.io/stfbln/ingot/nuget/index.json" \
            -NupkgPushApiKey "${{ secrets.FEEDZ_API_KEY }}"
      - name: Push (nuget.org)
        if: ${{ startsWith(github.event.ref, 'refs/tags') }}
        run: |
          dotnet ib ci-src-publish \
            -NupkgDirectory "${{ env.NUPKG_DiRECTORY }}" \
            -NupkgPushSource "https://api.nuget.org/v3/index.json" \
            -NupkgPushApiKey "${{ secrets.NUGET_ORG_API_KEY }}"
