name: Ingot
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NUPKG_DiRECTORY: "./dist"
  NUPKG_PUSH_SOURCE: "https://api.nuget.org/v3/index.json"
  NUPKG_PUSH_API_KEY: "test"

jobs:
  libs:
    name: Libraries
    runs-on: ubuntu-latest
    # container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    steps:
      - uses: actions/setup-dotnet@v4
        name: Setup dotnet
        with:
          dotnet-version: '9.0.x'
      - uses: actions/checkout@v4
        name: Checkout
      - name: Setup
        run: |
          dotnet tool restore
          dotnet ib Setup
      - name: Build
        run: dotnet ib Build
      - name: Test
        run: dotnet test ./src/Tests/Mediator/Ingot.Mediator.Abstractions.Tests/Ingot.Mediator.Abstractions.Tests.csproj --no-build --verbosity diagnostic > ./output.txt
      - uses: actions/upload-artifact@v4
        name: "Artifact: dotnet test output"
        if: always()
        with:
          name: test-output
          if-no-files-found: error
          retention-days: 3
          path: ./output.txt
      - name: Validate
        run: dotnet ib Validate
      - name: Package
        run: |
          dotnet ib Package \
            -NupkgDirectory ${{ env.NUPKG_DiRECTORY }}
      - uses: actions/upload-artifact@v4
        name: "Artifact: nuget"
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 3
          path: ${{ env.NUPKG_DiRECTORY }}/*.nupkg
      - name: Release
        run: |
          dotnet ib Release \
            -NupkgDirectory ${{ env.NUPKG_DiRECTORY }} \
            -NupkgPushSource ${{ env.NUPKG_PUSH_SOURCE }} \
            -NupkgPushApiKey ${{ env.NUPKG_PUSH_API_KEY }}
