name: Ingot Source (Staging)

on:
  push:
    tags-ignore:
      - '**'
    paths:
      - 'src/**'
      - '.github/**'
      - '**/.build.ps1'
      - '**/global.json'
      - '**/dotnet-tools.json'
      - '**/nuget.config'
      - '**/*.props'
    branches:
      - main
  pull_request:
    paths:
      - 'src/**'
      - '.github/**'
      - '**/.build.ps1'
      - '**/global.json'
      - '**/dotnet-tools.json'
      - '**/nuget.config'
      - '**/*.props'
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  build-test-validate:
    name: Source
    uses: stfbln/ingot/.github/workflows/ingot-src-build-test-validate.yml@main

  src-publish-feedz:
    needs:
      - build-test-validate
    name: Source / Publish (feedz.io)
    runs-on: ubuntu-24.04
    container: mcr.microsoft.com/dotnet/sdk:9.0.102-noble
    cancel-timeout-minutes: 5
    timeout-minutes: 5
    steps:
      - uses: stfbln/ingot/.github/actions/ingot-setup@main
        name: Setup
      - name: Push
        uses: ./.github/actions/ingot-src/package-publish
        with:
          nuget-source: "https://f.feedz.io/stfbln/ingot/nuget/index.json"
          nuget-api-key: "${{ secrets.FEEDZ_API_KEY }}"
