name: Source (Release)

# Runs only on tags since
# it publishes to nuget.org
on:
  push:
    tags:
      - '*'

jobs:
  
  # Builds, test and validate the source code
  # it finishes by uploading the nuget packages
  # as an artifact.
  build-test-validate:
    name: Source
    uses: stfbln/ingot/.github/workflows/source-build-test-validate.yml@main

  # Publishes the nuget packages
  # to nuget.org
  src-publish-nuget-org:
    needs: build-test-validate
    name: Source / Publish (nuget.org)
    runs-on: ubuntu-24.04
    container: stfbln/ingot:latest
    cancel-timeout-minutes: 5
    timeout-minutes: 5
    steps:
      
      # Gets git sources and ensures 
      # invoke build is initialized
      - uses: stfbln/ingot/.github/actions/setup@main
        name: Setup
      
      # Publishes the nuget packages
      # to nuget.org
      - name: Push
        uses: ./.github/actions/source/package-publish
        with:
          nuget-source: "https://api.nuget.org/v3/index.json"
          nuget-api-key: "${{ secrets.NUGET_ORG_API_KEY }}"
